<a href="https://colab.research.google.com/github/Amaliaaap/Machine-Learning/blob/main/Feature%20Engineering%20and%20Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FEATURE ENGINEERING AND SELECTION**

# **1. Menginput dataset**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML/used_cars_dataset.csv')
df.head()

,price,year,mileage,fuel_type,engine_size,transmission,num_owners,car_brand,color
0,20795,2007,141926,Petrol,1.2,Automatic,1,Tesla,Blue
1,5860,2002,100084,Hybrid,1.2,Automatic,4,Tesla,Black
2,43158,2002,179695,Petrol,1.0,Manual,4,Honda,Gray
3,49732,2000,17392,Diesel,1.0,Manual,1,Toyota,Red
4,16284,2004,65680,Petrol,1.0,Manual,1,Honda,Blue

# **2.**

a. Cek apakah terdapat missing values pada dataset. Jika ada, lakukan imputasi yang
sesuai untuk data numerik dan kategorikal.

b. Mengapa memilih metode imputasi yang digunakan?

c. Apakah ada kemungkinan bias jika kita mengisi missing values dengan median atau
modus?

In [ ]:
df.isnull().sum()

price           0
year            0
mileage         0
fuel_type       0
engine_size     0
transmission    0
num_owners      0
car_brand       0
color           0
dtype: int64

Berdasarkan hasil di atas, pada data tidak terdapat missing value

# **3.**

a. Ubah fitur kategorikal (fuel_type, transmission, car_brand, color) menjadi numerik
menggunakan **One-Hot Encoding** dan tampilkan hasilnya.

b. Apa dampak dari One-Hot Encoding terhadap jumlah fitur dalam dataset?

c. Jika dataset memiliki 100 kategori unik dalam satu fitur, apakah One-Hot Encoding
tetap efektif? Apa alternatifnya?

In [ ]:
df.dtypes

price             int64
year              int64
mileage           int64
fuel_type        object
engine_size     float64
transmission     object
num_owners        int64
car_brand        object
color            object
dtype: object

In [ ]:
df_encoded = pd.get_dummies(df, columns=['fuel_type', 'transmission', 'car_brand', 'color'])
df_encoded.head()

,price,year,mileage,engine_size,num_owners,fuel_type_Diesel,fuel_type_Electric,fuel_type_Hybrid,fuel_type_Petrol,transmission_Automatic,...,car_brand_BMW,car_brand_Ford,car_brand_Honda,car_brand_Tesla,car_brand_Toyota,color_Black,color_Blue,color_Gray,color_Red,color_White
0,20795,2007,141926,1.2,1,False,False,False,True,True,...,False,False,False,True,False,False,True,False,False,False
1,5860,2002,100084,1.2,4,False,False,True,False,True,...,False,False,False,True,False,True,False,False,False,False
2,43158,2002,179695,1.0,4,False,False,False,True,False,...,False,False,True,False,False,False,False,True,False,False
3,49732,2000,17392,1.0,1,True,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4,16284,2004,65680,1.0,1,False,False,False,True,False,...,False,False,True,False,False,False,True,False,False,False

One-Hot Encoding berdampak pada penambahan jumlah kolom dataser karena setiap kategori unik dalam fitur akan diubah menjadi kolom biner baru. Penggunaan One-Hot Encoding tentu tidak efektif jika ada 100 kategori unik dalam satu fitur, karena hal ini akan menyebabkan dimensi dataset menjadi lebih besar dan menyebabkan muncul banyak nilai nol.

# **4.**

a. Lakukan scaling pada fitur numerik (mileage, engine_size, num_owners) menggunakan **StandardScaler**.

b. Apa perbedaan hasil antara StandardScaler, MinMaxScaler, dan RobustScaler?

c. Dalam kondisi apa kita lebih baik menggunakan MinMaxScaler dibandingkan
StandardScaler?

In [ ]:
df.dtypes

price             int64
year              int64
mileage           int64
fuel_type        object
engine_size     float64
transmission     object
num_owners        int64
car_brand        object
color            object
dtype: object

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
import numpy as np
np.set_printoptions(suppress=True)

**Scaling menggunakan StandardScaler**

In [ ]:
views = ['mileage', 'engine_size', 'num_owners']
scaler = StandardScaler()
df_encoded[views]=scaler.fit_transform(df_encoded[views])
df_encoded.head()

,price,year,mileage,engine_size,num_owners,fuel_type_Diesel,fuel_type_Electric,fuel_type_Hybrid,fuel_type_Petrol,transmission_Automatic,...,car_brand_Honda,car_brand_Tesla,car_brand_Toyota,color_Black,color_Blue,color_Gray,color_Red,color_White,car_age,mileage_per_year
0,20795,2007,0.697751,-0.948936,-1.189562,False,False,False,True,True,...,False,True,False,False,True,False,False,False,18,0.017414
1,5860,2002,-0.078852,-0.948936,1.306023,False,False,True,False,True,...,False,True,False,True,False,False,False,False,23,-0.007474
2,43158,2002,1.398758,-1.225191,1.306023,False,False,False,True,False,...,True,False,False,False,False,True,False,False,23,0.032676
3,49732,2000,-1.613648,-1.225191,-1.189562,True,False,False,False,False,...,False,False,True,False,False,False,True,False,25,-0.045244
4,16284,2004,-0.717404,-1.225191,-1.189562,False,False,False,True,False,...,True,False,False,False,True,False,False,False,21,-0.027189

**Scaling menggunakan MinMaxScaler**

In [ ]:
views = ['mileage', 'engine_size', 'num_owners']
scaler = MinMaxScaler()
df_encoded[views]=scaler.fit_transform(df_encoded[views])
df_encoded.head()

,price,year,mileage,engine_size,num_owners,fuel_type_Diesel,fuel_type_Electric,fuel_type_Hybrid,fuel_type_Petrol,transmission_Automatic,...,car_brand_BMW,car_brand_Ford,car_brand_Honda,car_brand_Tesla,car_brand_Toyota,color_Black,color_Blue,color_Gray,color_Red,color_White
0,20795,2007,0.710846,0.1,0.0,False,False,False,True,True,...,False,False,False,True,False,False,True,False,False,False
1,5860,2002,0.480380,0.1,1.0,False,False,True,False,True,...,False,False,False,True,False,True,False,False,False,False
2,43158,2002,0.918878,0.0,1.0,False,False,False,True,False,...,False,False,True,False,False,False,False,True,False,False
3,49732,2000,0.024913,0.0,0.0,True,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4,16284,2004,0.290883,0.0,0.0,False,False,False,True,False,...,False,False,True,False,False,False,True,False,False,False

**Scaling menggunakan RobustScaler**

In [ ]:
views = ['mileage', 'engine_size', 'num_owners']
scaler = RobustScaler()
df_encoded[views]=scaler.fit_transform(df_encoded[views])
df_encoded.head()

,price,year,mileage,engine_size,num_owners,fuel_type_Diesel,fuel_type_Electric,fuel_type_Hybrid,fuel_type_Petrol,transmission_Automatic,...,car_brand_BMW,car_brand_Ford,car_brand_Honda,car_brand_Tesla,car_brand_Toyota,color_Black,color_Blue,color_Gray,color_Red,color_White
0,20795,2007,0.313444,-0.615385,-0.666667,False,False,False,True,True,...,False,False,False,True,False,False,True,False,False,False
1,5860,2002,-0.171906,-0.615385,0.333333,False,False,True,False,True,...,False,False,False,True,False,True,False,False,False,False
2,43158,2002,0.751549,-0.769231,0.333333,False,False,False,True,False,...,False,False,True,False,False,False,False,True,False,False
3,49732,2000,-1.131098,-0.769231,-0.666667,True,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4,16284,2004,-0.570978,-0.769231,-0.666667,False,False,False,True,False,...,False,False,True,False,False,False,True,False,False,False

Perbedaan hasil antara StandardScaler, MinMaxScaler, dan RobustScaler adalah

1. StandarScaler mengubah data sehingga memiliki mean 0 dan standar deviasi 1 dan hasil scaling bisa negatif maupun positif.

2. MinMacScaler mengubah data ke dalan rentang 0 hingga 1 sehingga hasil scaling ada di antara o dan 1.

3. RobustScaler menggunakan median untuk scaling sehingga lebih tahan terhadap outlier, karena tidak menggunakan mean dan standar deviasi seperti StandardScaler.


Jadi, MinMaxScaler lebih baik digunakan jika data tidak berdistribusi normal dan data memiliki batasan nilai yang jelas. Misalnya, jika fitur memiliki rentang tetap, maka MinMaxScaler akan menjaga skala data tetap dalam batas yang wajar.

# **5.**

a. Buat fitur baru car_age yang menunjukkan usia mobil berdasarkan tahun saat ini (2025).

b. Apakah fitur car_age lebih informatif dibandingkan fitur asli year? Jelaskan alasannya

In [ ]:
df_encoded['car_age']=2025-df_encoded['year']
df_encoded.head()

,price,year,mileage,engine_size,num_owners,fuel_type_Diesel,fuel_type_Electric,fuel_type_Hybrid,fuel_type_Petrol,transmission_Automatic,...,car_brand_Ford,car_brand_Honda,car_brand_Tesla,car_brand_Toyota,color_Black,color_Blue,color_Gray,color_Red,color_White,car_age
0,20795,2007,0.313444,-0.615385,-0.666667,False,False,False,True,True,...,False,False,True,False,False,True,False,False,False,18
1,5860,2002,-0.171906,-0.615385,0.333333,False,False,True,False,True,...,False,False,True,False,True,False,False,False,False,23
2,43158,2002,0.751549,-0.769231,0.333333,False,False,False,True,False,...,False,True,False,False,False,False,True,False,False,23
3,49732,2000,-1.131098,-0.769231,-0.666667,True,False,False,False,False,...,False,False,False,True,False,False,False,True,False,25
4,16284,2004,-0.570978,-0.769231,-0.666667,False,False,False,True,False,...,False,True,False,False,False,True,False,False,False,21

In [ ]:
# menampilkan car_age
df_encoded['car_age']

0     18
1     23
2     23
3     25
4     21
      ..
95     9
96     9
97    24
98    24
99     4
Name: car_age, Length: 100, dtype: int64

fitur car_age tentu lebih informatif jika dibandingkan dengan fitur year. Hal ini dikarenakan fitur car_age lebih mudah untuk interpretasi, karena jika melihat dari kolom year kita harus melakukan perhitungan mental untuk mengetahui usia mobil. Sedangkan fitur car_age langsung memberikan informasi yang lebih jelas mengenai usia mobil.

# **6.**

a. Buat fitur baru mileage_per_year dengan membagi mileage dengan car_age.

b. Mengapa mileage_per_year bisa menjadi fitur yang lebih informatif dibandingkan
mileage saja?

In [ ]:
views = ['mileage', 'engine_size', 'num_owners']
scaler = StandardScaler()
df_encoded[views]=scaler.fit_transform(df_encoded[views])
df_encoded.head()

df_encoded['mileage_per_year']=df_encoded['mileage']/df_encoded['car_age']
df_encoded.head()

,price,year,mileage,engine_size,num_owners,fuel_type_Diesel,fuel_type_Electric,fuel_type_Hybrid,fuel_type_Petrol,transmission_Automatic,...,car_brand_Honda,car_brand_Tesla,car_brand_Toyota,color_Black,color_Blue,color_Gray,color_Red,color_White,car_age,mileage_per_year
0,20795,2007,0.697751,-0.948936,-1.189562,False,False,False,True,True,...,False,True,False,False,True,False,False,False,18,0.038764
1,5860,2002,-0.078852,-0.948936,1.306023,False,False,True,False,True,...,False,True,False,True,False,False,False,False,23,-0.003428
2,43158,2002,1.398758,-1.225191,1.306023,False,False,False,True,False,...,True,False,False,False,False,True,False,False,23,0.060816
3,49732,2000,-1.613648,-1.225191,-1.189562,True,False,False,False,False,...,False,False,True,False,False,False,True,False,25,-0.064546
4,16284,2004,-0.717404,-1.225191,-1.189562,False,False,False,True,False,...,True,False,False,False,True,False,False,False,21,-0.034162

In [ ]:
df_encoded['mileage_per_year']

0     0.038764
1    -0.003428
2     0.060816
3    -0.064546
4    -0.034162
        ...
95   -0.034703
96   -0.188622
97   -0.034201
98    0.013892
99   -0.000712
Name: mileage_per_year, Length: 100, dtype: float64

Fitur mileage_per_year lebih informatif dibandingkan mileage saja karena fitur ini menggambarkan penggunaan mobil secara relatif. Jika Mileage hanya menunjukkan total jarak tempuh mobil tanpa memperhitungkan usia mobil, maka mileage_per_year mampu menunjukkan seberapa sering mobil digunakan per tahun sehingga bisa lebih relevan untuk menilai kondisi mobil.